# Generated by Django 5.0.6 on 2024-06-05 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="نام دسته"
                    ),
                ),
                (
                    "url_title",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="عنوان در url"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        null=True,
                        upload_to="images/category",
                        verbose_name="تصویر دسته",
                    ),
                ),
                ("is_active", models.BooleanField(verbose_name="فعال / غیرفعال")),
            ],
            options={
                "verbose_name": "دسته",
                "verbose_name_plural": "دسته ها",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان محصول")),
                (
                    "Image",
                    models.ImageField(
                        upload_to="images/products", verbose_name="تصویر محصول"
                    ),
                ),
                ("start_price", models.IntegerField(verbose_name="قیمت ابتدایی")),
                ("description", models.TextField(verbose_name="توضیحات محصول")),
                ("time", models.DurationField(verbose_name="مدت زمان حراجی")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="فعال / غیرفعال"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product_module.productcategory",
                        verbose_name="دسته محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "محصول",
                "verbose_name_plural": "محصولات",
            },
        ),
    ]
