# Generated by Django 5.0.6 on 2024-06-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategory",
            name="image",
            field=models.FileField(
                null=True, upload_to="images/category", verbose_name="تصویر دسته"
            ),
        ),
    ]
