# Generated by Django 5.0.6 on 2024-06-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0003_product_end_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="time",
            field=models.DateTimeField(verbose_name="مدت زمان حراجی"),
        ),
    ]
