# Generated by Django 5.0.6 on 2024-06-06 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_module", "0005_product_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product_module.productcategory",
                verbose_name="دسته محصول",
            ),
        ),
    ]
