# Generated by Django 5.0.6 on 2024-06-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=300, verbose_name="ایمیل")),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="نام و نام خانوادگی"),
                ),
                ("message", models.TextField(verbose_name="متن تماس با ما")),
                (
                    "created_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "response",
                    models.TextField(blank=True, null=True, verbose_name="پاسخ"),
                ),
                (
                    "is_read_by_admin",
                    models.BooleanField(
                        default=False, verbose_name="خوانده شده / نشده"
                    ),
                ),
            ],
            options={
                "verbose_name": "تماس با ما",
                "verbose_name_plural": "لیست تماس با ما",
            },
        ),
    ]
